theme: jekyll-theme-primer

title: InsTAL party
description: Contenus et info pour l'install party du master PluriTAL
emojicon: ğŸ§

url: https://loicgrobol.github.io/
baseurl: /insTAL-party/
repository: LoicGrobol/insTAL-party

include:
  - _pages
